version: '3'
services:
  web:
    # 7ajf-bfnx-75a9 mortimerwebsite pkze-sr6v-rbbv
    # command: odoo -d base-demo --without-demo=all --load-language=en_GB -i base,web
    image: odoo:14.0
    # platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8001:8069"
    volumes:
      - ./config:/etc/odoo
      - ../addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    # volumes:
    #   - ../data/odoo-db-data-base:/var/lib/postgresql/data
