version: '3'
services:
  web:
    # command: odoo -d base-demo --without-demo=all --load-language=en_GB -i base,web
    # command: odoo -d rd-demo --without-demo=all -u estate,estate_account --dev xml
    image: odoo:13.0
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8001:8069"
    # volumes:
    #   - ./custom:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ../data/odoo-db-data-base:/var/lib/postgresql/data
