version: '3'
services:
  web:
    build:
      context: .
    # 7ajf-bfnx-75a9 mortimerwebsite pkze-sr6v-rbbv UA-206803509-1
    # command: odoo --db_port=5432
    image: odoo-gcpcloudrun:14.0
    # platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8001:8069"
    # volumes:
    #   - ./config:/etc/odoo
    #   - ./custom:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    # volumes:
    #   - ../data/odoo-db-data-base:/var/lib/postgresql/data
